FROM python:3.13-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

COPY src/db/pyproject.toml src/db/uv.lock ./
COPY src/db/src/ ./src/

RUN uv sync --frozen --no-dev

COPY src/db/alembic.ini ./
COPY src/db/alembic/ ./alembic/

CMD ["uv", "run", "alembic", "upgrade", "head"]
